// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Microsoft.Agents.Protocols.Primitives
{
    /// <summary> The status of a particular token. </summary>
    public class TokenStatus
    {
        public TokenStatus() { }

        /// <summary> Initializes a new instance of TokenStatus. </summary>
        /// <param name="channelId"> The channelId of the token status pertains to. </param>
        /// <param name="connectionName"> The name of the connection the token status pertains to. </param>
        /// <param name="hasToken"> True if a token is stored for this ConnectionName. </param>
        /// <param name="serviceProviderDisplayName"> The display name of the service provider for which this Token belongs to. </param>
        public TokenStatus(string channelId = default, string connectionName = default, bool? hasToken = default, string serviceProviderDisplayName = default)
        {
            ChannelId = channelId;
            ConnectionName = connectionName;
            HasToken = hasToken;
            ServiceProviderDisplayName = serviceProviderDisplayName;
        }

        /// <summary> The channelId of the token status pertains to. </summary>
        public string ChannelId { get; set; }
        /// <summary> The name of the connection the token status pertains to. </summary>
        public string ConnectionName { get; set; }
        /// <summary> True if a token is stored for this ConnectionName. </summary>
        public bool? HasToken { get; set; }
        /// <summary> The display name of the service provider for which this Token belongs to. </summary>
        public string ServiceProviderDisplayName { get; set; }
    }
}
